# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firewall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(blank=True, help_text='Password or optional private key password if using key based authentication.', max_length=255, null=True)),
                ('private_key', models.CharField(blank=True, help_text='Optional private key file name if using key based authentication', max_length=255, null=True)),
                ('device_type', models.PositiveSmallIntegerField(choices=[(100, b'juniper_srx'), (200, b'palo_alto'), (201, b'palo_alto_panorama')], help_text='Orangengine device type.')),
                ('refresh_interval', models.PositiveIntegerField(default=15, help_text='Policy refresh interval in minutes')),
                ('panorama_device_group', models.CharField(blank=True, max_length=255, null=True)),
                ('palo_alto_api_key', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
