# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0001_firewall'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewall',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
