# firewall device types
F_DEVICE_TYPE_JUNIPER_SRX = 100
F_DEVICE_TYPE_PALO_ATLO = 200
F_DEVICE_TYPE_PALO_ATLO_PANORAMA = 201
F_DEVICE_TYPE_CHOICES = (
    (F_DEVICE_TYPE_JUNIPER_SRX, "juniper_srx"),
    (F_DEVICE_TYPE_PALO_ATLO, 'palo_alto'),
    (F_DEVICE_TYPE_PALO_ATLO_PANORAMA, 'palo_alto_panorama'),
)

F_DEVICE_TYPE_PALO_ALTO_CHOICES = [
    F_DEVICE_TYPE_PALO_ATLO,
    F_DEVICE_TYPE_PALO_ATLO_PANORAMA
]
